### ISSUE TITLE
I want to learn to write games like you, what knowledge do I need to master?

### ISSUE THREAD

**Issue by tuohao1125** [Martyn0324/SerpentAI#12]
I want to learn to write games like you, what knowledge do I need to master?

**Comment by Martyn0324** [comment]
Hey! Sorry for such a late reply, I didn't get notified about this post.

I actually don't know how to write games, I'm no game developer, so I can't really help you with that. I only know about Machine Learning.

However, it might be interesting for you to take a look at the library PyGame, which can give you some help. If you want to start with something more simple, like a Visual Novel, you could also try Ren'Py.
