### ISSUE TITLE
Thank fork for his work

### ISSUE THREAD

**Issue by monkeycc** [Martyn0324/SerpentAI#5]
Thank fork for his work

I have a problem here

------------

simulator：     VirtuaNES 
game：           Super Mario Bros
WIN10-11

```

# VirtuaNES 
# https://www.emulator-zone.com/doc.php/nes/virtuanes.html

# Super Mario Bros ROM
# https://wowroms.com/en/roms/nintendo-entertainment-system/download-super-mario-bros./23755.html
```
----------

Can I add a tutorial for windows

Like playing Super Mario Bros with virtuanes

Tutorial required

<img width="365" alt="1111111111111111" src="https://user-images.githubusercontent.com/6490927/141604978-9c8afebe-2693-45a7-92fd-27d9858fd8db.png">

**Comment by Martyn0324** [comment]
Hey! Yes, of course! If you create a repository with this tutorial I'll make it available in the wiki, perhaps in the [Community Showcase](https://github.com/Martyn0324/SerpentAI/wiki/Community-Showcase)

However, if the idea is to play NES games, I don't know if SerpentAI would be better than using OpenAI's Gym. But you can give it a try as you wish.

**Comment by Martyn0324** [comment]
I've enabled the editing in the wiki for everyone. Just create a new page and write the tutorial.

**Comment by monkeycc** [comment]
I want to play all the games

Such as Android games and windows  games

NES games allows me to simply match the learning environment

However, I am not familiar with the framework and do not know how to implement it

```
# Get process
os.getpid()

# Get an image of the process
from mss import mss

# Operate mouse and keyboard
pyautogui
```

**Comment by Martyn0324** [comment]
Then you should take a look at the [Community Plugin Showcase](https://github.com/Martyn0324/SerpentAI/wiki/Community-Showcase). There, you'll find some codes that may help you. I did pretty much based on what I saw there, especially using the AIsaac which is the most recent code made by SerpentAI's founder himself.
There's also some recorded livestreams in [SerpentAI's Youtube channel](https://www.youtube.com/c/SerpentAI/videos). However, the most recent video is the tutorial, which is from 2018, before PPO and RainbowDQN got implemented into the framework.

Unfortunately, SerpentAI doesn't have any documentation, so you'll have to copy+paste some code and see what each command does. It may also be interesting to dig into `/env/[environment_name]/Lib/site-packages/serpent` files to see what each thing does.

PS: My GameAgent codes are a Work In Progress, I'm trying to both optimize them and also solve some issues that sometimes I got me caught.

![hakisabh](https://user-images.githubusercontent.com/28028007/141886165-05c1f8a3-bee5-446c-aa9e-90f1ace9da2d.gif)

*Still needs more time into training*

**Comment by monkeycc** [comment]
Thanks for your help

Looking forward to your work
